# Generated by Django 4.1.1 on 2022-10-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_com', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=20)),
                ('dir_local', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('act_no_act', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('fecha_Nac', models.DateTimeField(verbose_name='Fecha nacimiento')),
                ('sexo', models.CharField(max_length=200)),
                ('listo_pro', models.BooleanField(default=False)),
                ('peso_actual', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('Observaciones', models.CharField(max_length=500)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trazabilidad.propietario')),
            ],
        ),
    ]
