# Generated by Django 4.1.1 on 2022-09-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
    ]
